### ISSUE TITLE
Can't open any model-file

### ISSUE THREAD

**Issue by mammuthus** [dukedev/hd_model_viewer#1]
HD Model Viewer (not pro) v0.25
Tablet Acer Iconia Tab p701 (Android 4.1.1)

So I made model in 3Ds MAX and want to view it on my tablet, but viewer can't open model file. I tried to open .3ds, .fbx, .mtl and .dae files. 
But I can't choose one to open it (see screenshot in attachement).

![Screenshot_2013-03-21-22-54-54 2 ](https://f.cloud.github.com/assets/1700286/287541/776e2cd6-925a-11e2-8f4c-e97693f78b31.png)

**Comment by dukedev** [comment]
This is a known issue with uppercase file extensions, and has been fixed. The workaround before the next release is to make the file extension lowercase, or use the search button in the file browser. Sorry for the hassle!
